# Generated by Django 5.1.5 on 2025-01-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors_movie_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='photo',
        ),
    ]
